/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;

import logica.DescontarPasaje;
import logica.ValidarPasaje;

/**
 *
 * @author ASUS
 */
public class PagarPasaje extends javax.swing.JInternalFrame {

    /**
     * Creates new form PersonzalizarTarjeta
     */
    public PagarPasaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel3.setText("Vender Tarjeta");

        jButton1.setText("Pagar Pasaje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese Su Numero De Tarjeta");

        jTextField1.setText("1010 0001 7507 6678");
        jTextField1.setText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("3500");
        jLabel2.setText("");
        jLabel4.setText("Valor Pagado:");
        jLabel4.setToolTipText("");

        jLabel5.setText("Saldo Disponible");

        jLabel6.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(jLabel2)
                        .addComponent(jButton1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField1))
                    .addComponent(jLabel4))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
String IdTarjeta = jTextField1.getText().trim();

        // Verificar si el campo de la tarjeta está en blanco
        if (IdTarjeta.isEmpty()) {
            // Mostrar un mensaje de error o tomar alguna acción apropiada
            // Por ejemplo, mostrar un diálogo o un mensaje en la interfaz
            JOptionPane.showMessageDialog(null, "Por favor, ingresa un número de tarjeta válido", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si el campo está en blanco
        }

        double ValorPasaje = 2950.0;
        double pasaje_descuento = ValorPasaje / 100 * 80;
        DescontarPasaje pagar = new DescontarPasaje();

        pagar.setIdTarjeta(IdTarjeta);
        pagar.setValorPasaje(ValorPasaje);
        int respuesta = pagar.validarPasaje();

        // traer metodo descontar pasaje
        // set tarjeta, para descontar pasaje
        ValidarPasaje consulta = new ValidarPasaje();
        consulta.setIdTarjeta(IdTarjeta);
        String valor;
        switch (respuesta) {
            case 1:
                jLabel2.setText("0");
                break;
            case 2:
                jLabel2.setText(Double.toString(ValorPasaje));

                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 3:
                jLabel2.setText("0");

                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 4:
                jLabel2.setText(Double.toString(pasaje_descuento));
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 5:
                jLabel2.setText(Double.toString(pasaje_descuento));
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 6:
                jLabel2.setText("0");
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 7:
                jLabel2.setText(Double.toString(ValorPasaje));
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 8:
                jLabel2.setText(Double.toString(ValorPasaje));
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 9:
                jLabel2.setText("0");
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            default:
                jLabel2.setText("0");
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
        }
        // TODO add your handling code here:sitp
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
        
    }
    // GEN-LAST:event_jTextField1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
