/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;

import logica.DescontarPasaje;
import logica.ValidarPasaje;

/**
 *
 * @author ASUS
 */
public class PagarPasaje extends javax.swing.JInternalFrame {

    /**
     * Creates new form PersonzalizarTarjeta
     */
    public PagarPasaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(14, 76, 117));

        jPanel2.setBackground(new java.awt.Color(50, 130, 181));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(188, 225, 247));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("0");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(188, 225, 247));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Valor Pagado:");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(188, 225, 247));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Saldo Disponible");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(188, 225, 247));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("0");

        jButton2.setBackground(new java.awt.Color(187, 225, 248));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Pagar Sitp");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(187, 225, 248));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Pagar Transmilenio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(188, 225, 247));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese Su Numero De Tarjeta");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(188, 225, 247));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pagar Pasaje");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        String IdTarjeta = jTextField1.getText().trim();

        // Verificar si el campo de la tarjeta está en blanco
        if (IdTarjeta.isEmpty()) {
            // Mostrar un mensaje de error o tomar alguna acción apropiada
            // Por ejemplo, mostrar un diálogo o un mensaje en la interfaz
            JOptionPane.showMessageDialog(null, "Por favor, ingresa un número de tarjeta válido", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si el campo está en blanco
        }

        double ValorPasaje = 2750.0;
        double pasaje_descuento = ValorPasaje / 100 * 80;
        DescontarPasaje pagar = new DescontarPasaje();

        pagar.setIdTarjeta(IdTarjeta);
        pagar.setValorPasaje(ValorPasaje);
        int respuesta = pagar.validarPasaje();

        // traer metodo descontar pasaje
        // set tarjeta, para descontar pasaje
        ValidarPasaje consulta = new ValidarPasaje();
        consulta.setIdTarjeta(IdTarjeta);
        String valor;
        switch (respuesta) {
            case 1:
                jLabel2.setText("0");
                break;
            case 2:
                jLabel2.setText(Double.toString(ValorPasaje));

                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 3:
                jLabel2.setText("0");

                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 4:
                jLabel2.setText(Double.toString(pasaje_descuento));
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 5:
                jLabel2.setText(Double.toString(pasaje_descuento));
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 6:
                jLabel2.setText("0");
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 7:
                jLabel2.setText(Double.toString(ValorPasaje));
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 8:
                jLabel2.setText(Double.toString(ValorPasaje));
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 9:
                jLabel2.setText("0");
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            default:
                jLabel2.setText("0");
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
        }
        // TODO add your handling code here:sitp
    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        String IdTarjeta = jTextField1.getText().trim();

        // Verificar si el campo de la tarjeta está en blanco
        if (IdTarjeta.isEmpty()) {
            // Mostrar un mensaje de error o tomar alguna acción apropiada
            // Por ejemplo, mostrar un diálogo o un mensaje en la interfaz
            JOptionPane.showMessageDialog(null, "Por favor, ingresa un número de tarjeta válido", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si el campo está en blanco
        }

        double ValorPasaje = 2950.0;
        double pasaje_descuento = ValorPasaje / 100 * 80;
        DescontarPasaje pagar = new DescontarPasaje();

        pagar.setIdTarjeta(IdTarjeta);
        pagar.setValorPasaje(ValorPasaje);
        int respuesta = pagar.validarPasaje();

        // traer metodo descontar pasaje
        // set tarjeta, para descontar pasaje
        ValidarPasaje consulta = new ValidarPasaje();
        consulta.setIdTarjeta(IdTarjeta);
        String valor;
        switch (respuesta) {
            case 1:
                jLabel2.setText("0");
                break;
            case 2:
                jLabel2.setText(Double.toString(ValorPasaje));

                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 3:
                jLabel2.setText("0");

                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 4:
                jLabel2.setText(Double.toString(pasaje_descuento));
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 5:
                jLabel2.setText(Double.toString(pasaje_descuento));
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 6:
                jLabel2.setText("0");
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 7:
                jLabel2.setText(Double.toString(ValorPasaje));
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 8:
                jLabel2.setText(Double.toString(ValorPasaje));
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            case 9:
                jLabel2.setText("0");
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
            default:
                jLabel2.setText("0");
                valor = consulta.consultarSaldo();
                jLabel6.setText(String.valueOf(valor));
                break;
        }
        // TODO add your handling code here:sitp
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed

    }
    // GEN-LAST:event_jTextField1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
